# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_axi_gpio_1_0/Lab_1_axi_gpio_1_0.xci
# IP: The module: 'Lab_1_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_axi_gpio_1_0/Lab_1_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_axi_gpio_1_0/Lab_1_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_axi_gpio_1_0/Lab_1_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Zynq_Book/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_axi_gpio_1_0/Lab_1_axi_gpio_1_0.xci
# IP: The module: 'Lab_1_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_axi_gpio_1_0/Lab_1_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_axi_gpio_1_0/Lab_1_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Zynq_Book/Lab_1/Lab_1.srcs/sources_1/bd/Lab_1/ip/Lab_1_axi_gpio_1_0/Lab_1_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
